server:
  port: 8080

spring:
  application:
    name: api-example
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3308/devaoc?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: admin
